//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Channels')
export class ChannelsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  channelName: string;

  @Column('text', { nullable: true })
  streamURL: string;

  @Column('text', { nullable: true })
  description: string;

  @Column('text', { nullable: true })
  genre: string;
}
