//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Channels: [
      {
        channelName: 'channelName 1',
        streamURL: 'streamURL 1',
        description: 'description 1',
        genre: 'genre 1',
        id: 76,
      },
      {
        channelName: 'channelName 2',
        streamURL: 'streamURL 2',
        description: 'description 2',
        genre: 'genre 2',
        id: 40,
      },
      {
        channelName: 'channelName 3',
        streamURL: 'streamURL 3',
        description: 'description 3',
        genre: 'genre 3',
        id: 25,
      },
      {
        channelName: 'channelName 4',
        streamURL: 'streamURL 4',
        description: 'description 4',
        genre: 'genre 4',
        id: 83,
      },
      {
        channelName: 'channelName 5',
        streamURL: 'streamURL 5',
        description: 'description 5',
        genre: 'genre 5',
        id: 95,
      },
    ],
  },
};
export default data;
