//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Channels: {
      name: 'Channels',
      fields: {
        channelName: 'Channel Name',
        streamURL: 'Stream Url',
        description: 'Description',
        genre: 'Genre',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Channels: {
      name: 'Channels (fr)',
      fields: {
        channelName: 'Channel Name (fr)',
        streamURL: 'Stream Url (fr)',
        description: 'Description (fr)',
        genre: 'Genre (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
